// Copyright (C) 2025  Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Altera and sold by Altera or its authorized distributors.  Please
// refer to the Altera Software License Subscription Agreements 
// on the Quartus Prime software download page.


// Generated by Quartus Prime Version 25.1 (Build Build 1129 10/21/2025)
// Created on Sun Sep 27 06:27:05 2026

control_for_fft control_for_fft_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.insignal(insignal_sig) ,	// input [11:0] insignal_sig
	.sink_valid(sink_valid_sig) ,	// output  sink_valid_sig
	.sink_ready(sink_ready_sig) ,	// output  sink_ready_sig
	.sink_error(sink_error_sig) ,	// output [1:0] sink_error_sig
	.sink_sop(sink_sop_sig) ,	// output  sink_sop_sig
	.sink_eop(sink_eop_sig) ,	// output  sink_eop_sig
	.inverse(inverse_sig) ,	// output  inverse_sig
	.outreal(outreal_sig) ,	// output [11:0] outreal_sig
	.outimag(outimag_sig) ,	// output [11:0] outimag_sig
	.fft_pts(fft_pts_sig) 	// output [10:0] fft_pts_sig
);

