// Copyright (C) 2025  Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Altera and sold by Altera or its authorized distributors.  Please
// refer to the Altera Software License Subscription Agreements 
// on the Quartus Prime software download page.


// Generated by Quartus Prime Version 25.1 (Build Build 1129 10/21/2025)
// Created on Sun Sep 27 10:34:35 2026

fft_wrapper fft_wrapper_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.in_signal(in_signal_sig) ,	// input [13:0] in_signal_sig
	.real_power(real_power_sig) ,	// output [24:0] real_power_sig
	.imag_power(imag_power_sig) ,	// output [24:0] imag_power_sig
	.fft_source_sop(fft_source_sop_sig) ,	// output  fft_source_sop_sig
	.sink_sop(sink_sop_sig) ,	// output  sink_sop_sig
	.sink_eop(sink_eop_sig) ,	// output  sink_eop_sig
	.sink_valid(sink_valid_sig) ,	// output  sink_valid_sig
	.reset_n(reset_n_sig) 	// output  reset_n_sig
);

